// <auto-generated />
namespace Inspinia_MVC5.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class RenameGeolocation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RenameGeolocation));
        
        string IMigrationMetadata.Id
        {
            get { return "201505310148500_RenameGeolocation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
